import { expect, test } from '@playwright/test'

test('25 分钟计划到收藏生词再刷新仍保留', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('今天，向前走一点。')).toBeVisible()
  await expect(page.locator('.task-card').first()).toBeVisible()
  await page.getByRole('button', { name:'设置' }).click()
  const minutes = page.getByLabel('可用分钟')
  await minutes.fill('25'); await minutes.blur()
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'本站文本' }).click()
  await page.getByRole('button', { name:'开始阅读' }).first().click()
  await expect(page.getByRole('heading', { name:'A Small Lab, a Better Measurement' })).toBeVisible()
  await page.evaluate(() => {
    const node = document.querySelector('.article-text')!.firstChild!
    const text = node.textContent ?? ''
    const start = text.indexOf('systematic')
    const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + 'systematic'.length)
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range)
    ;(document.querySelector('.article-text') as HTMLElement).dispatchEvent(new MouseEvent('mouseup', { bubbles:true }))
  })
  await expect(page.getByRole('heading', { name:'systematic' })).toBeVisible()
  await page.getByRole('button', { name:/加入生词本/ }).click()
  await page.reload()
  await page.getByRole('button', { name:'单词' }).click()
  await expect(page.getByText('systematic', { exact:true }).last()).toBeVisible()
})

test('训练提交前隐藏解析，提交后自动判分', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'训练' }).click()
  await page.getByRole('button', { name:/开始训练/ }).last().click()
  await expect(page.getByText('正确答案：')).toHaveCount(0)
  for (const question of await page.locator('.question-card').all()) await question.locator('.option-list button').first().click()
  await page.getByRole('button', { name:'提交并判分' }).click()
  await expect(page.getByText(/题正确/)).toBeVisible()
})

test('单词专栏使用四选一并在作答后显示完整词卡', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'单词' }).click()
  await expect(page.getByRole('heading', { name:'单词专栏' })).toBeVisible()
  await page.getByRole('button', { name:/开始复习/ }).click()
  await expect(page.locator('.vocab-options button')).toHaveCount(4)
  await page.locator('.vocab-options button').first().click()
  await page.getByRole('button', { name:'确认答案' }).click()
  await expect(page.locator('.word-feedback')).toBeVisible()
  await expect(page.getByText('派生', { exact:true })).toBeVisible()
  await expect(page.getByText('搭配', { exact:true })).toBeVisible()
})

test('口语练习保存自评并自动形成记录', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'口语' }).click()
  await expect(page.getByRole('heading', { name:'每天开口 10 分钟' })).toBeVisible()
  await page.getByRole('button', { name:/开始练习/ }).first().click()
  await expect(page.getByRole('heading', { name:'中国日报｜60 秒介绍全国两会' })).toBeVisible()
  await page.getByPlaceholder(/少用 um/).fill('先说结论，再补充例子。')
  await page.getByRole('button', { name:'完成并保存记录' }).click()
  await expect(page.getByRole('heading', { name:'今天已经真正开口了' })).toBeVisible()
  await page.getByRole('button', { name:'返回口语专栏' }).click()
  await expect(page.getByText(/流利度 3\/5/).last()).toBeVisible()
})

test('真人视频可站内打开且随手笔记刷新后保留', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'国外源' }).click()
  await page.getByRole('button', { name:'短视频', exact:true }).click()
  await page.getByText('Dirt-powered sensors help farmers optimize their fields').locator('..').getByRole('button', { name:'站内播放视频' }).click()
  await expect(page.locator('.inline-media video')).toBeVisible()
  const note = page.getByPlaceholder(/01:24/)
  await note.fill('function words — 功能词')
  await note.blur()
  await page.waitForTimeout(300)
  await page.reload()
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'国外源' }).click()
  await page.getByRole('button', { name:'短视频', exact:true }).click()
  await page.getByText('Dirt-powered sensors help farmers optimize their fields').locator('..').getByRole('button', { name:'站内播放视频' }).click()
  await expect(page.getByPlaceholder(/01:24/)).toHaveValue('function words — 功能词')
  await expect(page.getByText(/有英文字幕\/画面文字|无可用字幕|字幕未核实/).first()).toBeVisible()
})

test('国内 B 站英文视频使用官方播放器站内打开', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'短视频', exact:true }).click()
  await page.getByText('60 秒英语说清全国两会').locator('..').getByRole('button', { name:'站内播放视频' }).click()
  await expect(page.locator('.inline-media iframe')).toHaveAttribute('src', /player\.bilibili\.com/)
  await expect(page.getByText('字幕未核实', { exact:true }).first()).toBeVisible()
})

test('非人工词表单词由内置英汉词典补全中文义', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'本站文本' }).click()
  await page.getByRole('button', { name:'开始阅读' }).first().click()
  await page.evaluate(() => {
    const container = document.querySelector('.article-text') as HTMLElement
    const node = container.firstChild!
    const start = (node.textContent ?? '').indexOf('laboratory')
    const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + 'laboratory'.length)
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range)
    container.dispatchEvent(new MouseEvent('mouseup', { bubbles:true }))
  })
  await expect(page.locator('input[value*="实验室"]')).toBeVisible()
})

test('后端 AI 返回后补全语境词卡', async ({ page }) => {
  await page.route('**/api/word-card', (route) => route.fulfill({ status:200, contentType:'application/json', body:JSON.stringify({ card:{ pos:'n.', phonetic:'/ˈlæbrətɔːri/', meaningZh:'实验室', englishDefinition:'a room used for scientific work', explanation:'这里指学生进行测量实验的实验室。', wordParts:'labor + -atory', example:'The students tested the sensor in another laboratory.', derivatives:['laboratory-based'], collocations:['research laboratory'], synonyms:['lab'], antonyms:[] } }) }))
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('english-loop-ai-credential:local', JSON.stringify({ apiKey:'sk-test-key-long-enough', model:'deepseek-flash' })))
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'本站文本' }).click()
  await page.getByRole('button', { name:'开始阅读' }).first().click()
  await page.evaluate(() => {
    const container = document.querySelector('.article-text') as HTMLElement
    const node = container.firstChild!; const start = (node.textContent ?? '').indexOf('laboratory')
    const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + 10)
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range)
    container.dispatchEvent(new MouseEvent('mouseup', { bubbles:true }))
  })
  await expect(page.getByText('这里指学生进行测量实验的实验室。')).toBeVisible()
  await expect(page.getByText('AI 已根据当前句生成完整词卡；这是辅助解释，请确认后再收藏。')).toBeVisible()
})

test('点词卡显示完整语境词典信息', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'本站文本' }).click()
  await page.getByRole('button', { name:'开始阅读' }).first().click()
  await page.evaluate(() => {
    const container = document.querySelector('.article-text') as HTMLElement
    const node = container.firstChild!
    const start = (node.textContent ?? '').indexOf('microelectronics')
    const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + 'microelectronics'.length)
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range)
    container.dispatchEvent(new MouseEvent('mouseup', { bubbles:true }))
  })
  await expect(page.getByRole('heading', { name:'microelectronics' })).toBeVisible()
  await expect(page.getByText('/ˌmaɪkroʊɪˌlekˈtrɑːnɪks/')).toBeVisible()
  await expect(page.getByText('英文释义', { exact:true })).toBeVisible()
  await expect(page.getByText('构词拆解', { exact:true })).toBeVisible()
  await expect(page.locator('input[value="微电子学；微电子技术"]')).toBeVisible()
  await expect(page.getByText('microelectronics engineering')).toBeVisible()
})

test('VOA 真人音频和文章可在同一页面听读', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'内容' }).click()
  await page.getByRole('button', { name:'国外源' }).click()
  await page.getByRole('button', { name:'站内听读' }).first().click()
  await expect(page.locator('.inline-media audio')).toBeVisible()
  await expect(page.locator('.article-text')).toBeVisible()
  await expect(page.getByText('选中单词或短语，查看并确认此处含义')).toBeVisible()
})

test('侧边栏 AI 接口可按当前设备保存并测试配置', async ({ page }) => {
  await page.route('**/api/ai/test', (route) => route.fulfill({ status:200, contentType:'application/json', body:JSON.stringify({ ok:true, model:'deepseek-flash', preview:'可靠的' }) }))
  await page.route('**/api/ai/chat', (route) => route.fulfill({ status:200, contentType:'application/json', body:JSON.stringify({ answer:'这里使用现在完成时，因为动作与现在仍有关联。', model:'deepseek-flash' }) }))
  await page.goto('/')
  await page.getByRole('button', { name:'AI 接口' }).click()
  await expect(page.getByRole('heading', { name:'AI 接口' })).toBeVisible()
  await page.getByLabel('API Key').fill('sk-test-key-long-enough')
  await page.getByRole('button', { name:'保存到当前设备' }).click()
  await expect(page.getByText('可用于语境词卡')).toBeVisible()
  await page.getByRole('button', { name:'测试连接' }).click()
  await expect(page.getByText(/连接成功/)).toBeVisible()
  await page.getByPlaceholder(/输入英语问题/).fill('为什么这里用 has been？')
  await page.getByRole('button', { name:'发送' }).click()
  await expect(page.getByText(/现在完成时/)).toBeVisible()
})

test('单词过关后排到队尾并穿插其他单词', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'单词' }).click()
  await page.getByRole('button', { name:/开始复习/ }).click()
  const firstWord = (await page.locator('.word-audio').innerText()).trim()
  await page.getByRole('button', { name:/微电子学；微电子技术/ }).click()
  await page.getByRole('button', { name:'确认答案' }).click()
  await page.getByRole('button', { name:/先练下一个词/ }).click()
  await expect(page.locator('.mode-label')).toContainText('识义')
  await expect(page.locator('.word-audio')).not.toContainText(firstWord)
})

test('训练页在右上角切换国内与国外材料', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'训练' }).click()
  await expect(page.getByText('国内时政科技｜AI 如何进入中国—东盟贸易')).toBeVisible()
  await expect(page.getByText('真人慢速新闻｜激光如何改变世界')).not.toBeVisible()
  await page.getByRole('button', { name:'国外来源' }).click()
  await expect(page.getByText('真人慢速新闻｜激光如何改变世界')).toBeVisible()
  await expect(page.getByText('国内时政科技｜AI 如何进入中国—东盟贸易')).not.toBeVisible()
})

test('内容页只展示可站内完成的扩充材料', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'内容' }).click()
  await expect(page.getByText('When One Tiny Defect Changes a Whole Chip')).toBeVisible()
  await expect(page.getByText('China Sci-Tech｜中国科技英文报道入口')).not.toBeVisible()
  await expect(page.locator('.content-card')).toHaveCount(11)
  await page.getByText('When One Tiny Defect Changes a Whole Chip').locator('..').getByRole('button', { name:'开始阅读' }).click()
  await expect(page.locator('.article-text')).toContainText('Engineers therefore pay close attention to yield')
})

test('设置考试目标后自动匹配词书并筛选训练', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'设置' }).click()
  await page.getByRole('button', { name:'六级', exact:true }).click()
  await expect(page.getByLabel('当前词书')).toHaveValue('cet6-core')
  await page.getByRole('button', { name:'训练' }).click()
  await expect(page.getByText('六级进阶｜When Public Infrastructure Becomes Invisible')).toBeVisible()
  await expect(page.getByText('考研英语一｜The Metric Is Not the Goal')).not.toBeVisible()
  await page.getByRole('button', { name:'单词' }).click()
  await expect(page.getByText('mitigate', { exact:true })).toBeVisible()
  await expect(page.getByText('scrutinize', { exact:true })).not.toBeVisible()
})

test('课表 OCR 文字先形成可编辑草稿再导入', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'设置' }).click()
  await page.getByLabel('OCR 原始文字（可修正）').fill('周一 高等数学 第1-2节 单周\n星期三 大学英语 14:00-15:35 双周')
  await page.getByRole('button', { name:'重新解析下方文字' }).click()
  await expect(page.locator('.ocr-drafts article')).toHaveCount(2)
  await expect(page.getByLabel('候选开始时间').first()).toHaveValue('08:00')
  await page.getByRole('button', { name:'确认并导入完整课程' }).click()
  await expect(page.getByText('高等数学', { exact:true })).toBeVisible()
  await expect(page.getByText('大学英语', { exact:true })).toBeVisible()
})
