import { expect, test } from '@playwright/test'

test('历年真题资料按真实年份月份筛选并显示原卷链接', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button',{ name:'训练',exact:true }).click()
  await page.getByRole('button',{ name:'历年真题资料',exact:true }).click()
  await page.getByRole('combobox',{ name:'真题年份',exact:true }).selectOption('2026')
  await page.getByRole('combobox',{ name:'考试月份',exact:true }).selectOption('6')
  await expect(page.locator('.past-paper-row')).toHaveCount(1)
  await expect(page.locator('.past-paper-row')).toContainText('答案待补')
  await expect(page.locator('.past-paper-row a')).toHaveCount(3)
  expect(await page.locator('.past-paper-row a').first().getAttribute('href')).toContain('CET46-Resources/blob/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path:`test-results/past-papers-${test.info().project.name}.png`,fullPage:true })
})

test('口语接入内容库并可搜索复述素材', async ({ page }) => {
  await page.goto('/')
  if (!await page.getByRole('button', { name:'口语', exact:true }).isVisible()) await page.locator('.nav-more > summary').click()
  await page.getByRole('button', { name:'口语', exact:true }).click()
  await page.getByRole('button', { name:'国内源', exact:true }).click()
  await page.getByLabel('搜索口语素材').fill('Explain the Circuit')
  await expect(page.locator('.speaking-grid article')).toHaveCount(1)
  await page.getByRole('button', { name:/开始练习/ }).click()
  await expect(page.getByRole('heading', { name:'Explain the Circuit Without Hiding Behind Jargon' })).toBeVisible()
  await page.getByRole('button', { name:'完成并保存记录' }).click()
  await page.getByRole('button', { name:'返回口语专栏' }).click()
  await expect(page.getByLabel('搜索口语素材')).toBeVisible()
})

test('逐题核对锁定作答，答题卡显示进度', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name:'训练', exact:true }).click()
  await page.getByRole('combobox',{name:'题目来源',exact:true}).selectOption('original')
  await page.getByLabel('作答模式').selectOption('practice')
  await page.getByRole('button', { name:/开始训练/ }).first().click()
  const question = page.locator('.question-card').first()
  await expect(question.locator('.explanation')).toHaveCount(0)
  await question.locator('.option-list button').first().click()
  await question.getByRole('button', { name:'核对本题答案' }).click()
  await expect(question.locator('.explanation')).toBeVisible()
  await expect(question.locator('.option-list button').first()).toBeDisabled()
  await expect(page.getByRole('navigation', { name:'答题卡' })).toContainText('已答 1/')
})

test('选词填空可标记、交卷、查看历史并重练错题', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button',{ name:'训练',exact:true }).click()
  await page.getByRole('combobox',{name:'题目来源',exact:true}).selectOption('original')
  await page.getByRole('combobox',{ name:'题型',exact:true }).selectOption('cloze')
  await expect(page.locator('.training-card')).toHaveCount(2)
  await page.getByRole('button',{ name:/开始训练/ }).first().click()
  const first = page.locator('.question-card').first()
  await expect(first.locator('.option-list button')).toHaveCount(15)
  await first.getByRole('button',{ name:'标记本题' }).click()
  await first.locator('.option-list button').first().click()
  await page.getByRole('button',{ name:/提交并判分/ }).click()
  await expect(page.getByRole('heading',{ name:'0/10 题正确 · 0%' })).toBeVisible()
  await page.getByRole('button',{ name:'← 返回训练列表' }).click()
  await page.getByRole('button',{ name:/训练记录 ·/ }).click()
  await page.getByRole('button',{ name:'查看答案与解析' }).click()
  await expect(page.getByRole('button',{ name:'取消标记' })).toBeVisible()
  await expect(first.locator('.explanation')).toBeVisible()
  await page.getByRole('button',{ name:/重练错题与不确定题/ }).click()
  await expect(page.locator('.question-card')).toHaveCount(10)
  await expect(page.locator('.explanation')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path:`test-results/training-${test.info().project.name}.png`,fullPage:true })
})

test('写作草稿恢复、提交与历史反馈入口', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button',{ name:'训练',exact:true }).click()
  await page.getByRole('combobox',{name:'题目来源',exact:true}).selectOption('original')
  await page.getByRole('combobox',{ name:'题型',exact:true }).selectOption('writing')
  await page.getByRole('button',{ name:/开始训练/ }).first().click()
  const text = 'A regular study routine helps students understand difficult ideas. I plan one focused hour every day.'
  await page.getByLabel('你的英文作答').fill(text)
  await expect(page.getByText('查看参考与讲解')).toHaveCount(0)
  await page.getByRole('button',{ name:'← 保存并退出' }).click()
  await page.getByRole('button',{ name:'继续',exact:true }).click()
  await expect(page.getByLabel('你的英文作答')).toHaveValue(text)
  await page.getByRole('button',{ name:'继续',exact:true }).click()
  await page.getByRole('button',{ name:'提交并查看参考' }).click()
  await expect(page.getByRole('heading',{ name:'作答已保存' })).toBeVisible()
  await page.getByText('查看参考与讲解').click()
  await expect(page.locator('.written-reference-text')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path:`test-results/writing-${test.info().project.name}.png`,fullPage:true })
  await page.getByRole('button',{ name:'← 返回训练列表' }).click()
  await page.getByRole('button',{ name:/训练记录 ·/ }).click()
  await page.getByRole('button',{ name:'查看作答与反馈' }).click()
  await expect(page.getByLabel('你的英文作答')).toHaveValue(text)
  await expect(page.getByLabel('你的英文作答')).toBeDisabled()
})
