import { expect, test } from '@playwright/test'

test('首页进度、下一项和收拢导航保持可用', async ({ page }) => {
  await page.route('**/api/content-feed', (route) => route.fulfill({ json:{ items:[] } }))
  await page.goto('/')
  await expect(page.locator('.task-card').first()).toBeVisible()
  const count = await page.locator('.task-card').count()
  await expect(page.getByRole('progressbar', { name:'今日任务完成进度' })).toHaveAttribute('value', '0')
  await page.locator('.task-card').first().getByRole('button', { name:'完成', exact:true }).click()
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', String(Math.round(100 / count)))
  await page.reload()
  await expect(page.locator('.task-card.completed')).toHaveCount(1)
  await expect(page.locator('.next-task')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path:`test-results/workspace-home-${test.info().project.name}.png`, fullPage:true })
  await page.locator('.next-task').click()
  await expect(page.locator('.today-console')).toHaveCount(0)
  await page.getByRole('button', { name:'今天', exact:true }).click()
  await expect(page.locator('.next-task')).toHaveText('继续学习')
  await page.locator('.nav-more > summary').click()
  await page.getByRole('button', { name:'设置', exact:true }).click()
  await expect(page.locator('.page-settings')).toBeVisible()
  await expect(page.locator('.nav-more')).not.toHaveAttribute('open')
  await page.getByRole('button', { name:'训练', exact:true }).click()
  await expect(page.getByRole('heading', { name:'英语训练', exact:true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path:`test-results/workspace-training-${test.info().project.name}.png` })
  await page.getByRole('button', { name:'内容', exact:true }).click()
  await expect(page.getByRole('button', { name:'换一批' })).toBeVisible()
  await expect(page.getByRole('button', { name:'更新官方源' })).not.toBeVisible()
  await page.getByText('更多操作', { exact:true }).click()
  await expect(page.getByRole('button', { name:'更新官方源' })).toBeVisible()
  await expect(page.getByRole('button', { name:'导入内容 JSON' })).toBeVisible()
})
